[project]
name = "first-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "pandas>=2.0.0",
    "openpyxl>=3.1.0",
    "google-generativeai>=0.3.0",
]
